// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package access_point

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go/aws"
	svcsdk "github.com/aws/aws-sdk-go/service/s3control"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/s3control-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &aws.JSONValue{}
	_ = &svcsdk.S3Control{}
	_ = &svcapitypes.AccessPoint{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.GetAccessPointOutput
	resp, err = rm.sdkapi.GetAccessPointWithContext(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetAccessPoint", err)
	if err != nil {
		if reqErr, ok := ackerr.AWSRequestFailure(err); ok && reqErr.StatusCode() == 404 {
			return nil, ackerr.NotFound
		}
		if awsErr, ok := ackerr.AWSError(err); ok && awsErr.Code() == "UNKNOWN" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.AccessPointArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.AccessPointArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.Alias != nil {
		ko.Status.Alias = resp.Alias
	} else {
		ko.Status.Alias = nil
	}
	if resp.Bucket != nil {
		ko.Spec.Bucket = resp.Bucket
	} else {
		ko.Spec.Bucket = nil
	}
	if resp.BucketAccountId != nil {
		ko.Spec.BucketAccountID = resp.BucketAccountId
	} else {
		ko.Spec.BucketAccountID = nil
	}
	if resp.Name != nil {
		ko.Spec.Name = resp.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.PublicAccessBlockConfiguration != nil {
		f8 := &svcapitypes.PublicAccessBlockConfiguration{}
		if resp.PublicAccessBlockConfiguration.BlockPublicAcls != nil {
			f8.BlockPublicACLs = resp.PublicAccessBlockConfiguration.BlockPublicAcls
		}
		if resp.PublicAccessBlockConfiguration.BlockPublicPolicy != nil {
			f8.BlockPublicPolicy = resp.PublicAccessBlockConfiguration.BlockPublicPolicy
		}
		if resp.PublicAccessBlockConfiguration.IgnorePublicAcls != nil {
			f8.IgnorePublicACLs = resp.PublicAccessBlockConfiguration.IgnorePublicAcls
		}
		if resp.PublicAccessBlockConfiguration.RestrictPublicBuckets != nil {
			f8.RestrictPublicBuckets = resp.PublicAccessBlockConfiguration.RestrictPublicBuckets
		}
		ko.Spec.PublicAccessBlockConfiguration = f8
	} else {
		ko.Spec.PublicAccessBlockConfiguration = nil
	}
	if resp.VpcConfiguration != nil {
		f9 := &svcapitypes.VPCConfiguration{}
		if resp.VpcConfiguration.VpcId != nil {
			f9.VPCID = resp.VpcConfiguration.VpcId
		}
		ko.Spec.VPCConfiguration = f9
	} else {
		ko.Spec.VPCConfiguration = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Spec.AccountID == nil || r.ko.Spec.Name == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.GetAccessPointInput, error) {
	res := &svcsdk.GetAccessPointInput{}

	if r.ko.Spec.AccountID != nil {
		res.SetAccountId(*r.ko.Spec.AccountID)
	}
	if r.ko.Spec.Name != nil {
		res.SetName(*r.ko.Spec.Name)
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateAccessPointOutput
	_ = resp
	resp, err = rm.sdkapi.CreateAccessPointWithContext(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateAccessPoint", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.AccessPointArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.AccessPointArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.Alias != nil {
		ko.Status.Alias = resp.Alias
	} else {
		ko.Status.Alias = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateAccessPointInput, error) {
	res := &svcsdk.CreateAccessPointInput{}

	if r.ko.Spec.AccountID != nil {
		res.SetAccountId(*r.ko.Spec.AccountID)
	}
	if r.ko.Spec.Bucket != nil {
		res.SetBucket(*r.ko.Spec.Bucket)
	}
	if r.ko.Spec.BucketAccountID != nil {
		res.SetBucketAccountId(*r.ko.Spec.BucketAccountID)
	}
	if r.ko.Spec.Name != nil {
		res.SetName(*r.ko.Spec.Name)
	}
	if r.ko.Spec.PublicAccessBlockConfiguration != nil {
		f4 := &svcsdk.PublicAccessBlockConfiguration{}
		if r.ko.Spec.PublicAccessBlockConfiguration.BlockPublicACLs != nil {
			f4.SetBlockPublicAcls(*r.ko.Spec.PublicAccessBlockConfiguration.BlockPublicACLs)
		}
		if r.ko.Spec.PublicAccessBlockConfiguration.BlockPublicPolicy != nil {
			f4.SetBlockPublicPolicy(*r.ko.Spec.PublicAccessBlockConfiguration.BlockPublicPolicy)
		}
		if r.ko.Spec.PublicAccessBlockConfiguration.IgnorePublicACLs != nil {
			f4.SetIgnorePublicAcls(*r.ko.Spec.PublicAccessBlockConfiguration.IgnorePublicACLs)
		}
		if r.ko.Spec.PublicAccessBlockConfiguration.RestrictPublicBuckets != nil {
			f4.SetRestrictPublicBuckets(*r.ko.Spec.PublicAccessBlockConfiguration.RestrictPublicBuckets)
		}
		res.SetPublicAccessBlockConfiguration(f4)
	}
	if r.ko.Spec.VPCConfiguration != nil {
		f5 := &svcsdk.VpcConfiguration{}
		if r.ko.Spec.VPCConfiguration.VPCID != nil {
			f5.SetVpcId(*r.ko.Spec.VPCConfiguration.VPCID)
		}
		res.SetVpcConfiguration(f5)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (*resource, error) {
	return nil, ackerr.NewTerminalError(ackerr.NotImplemented)
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteAccessPointOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteAccessPointWithContext(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteAccessPoint", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteAccessPointInput, error) {
	res := &svcsdk.DeleteAccessPointInput{}

	if r.ko.Spec.AccountID != nil {
		res.SetAccountId(*r.ko.Spec.AccountID)
	}
	if r.ko.Spec.Name != nil {
		res.SetName(*r.ko.Spec.Name)
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.AccessPoint,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	// No terminal_errors specified for this resource in generator config
	return false
}
